export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_FETCH_SUCCEEDED = 'SIGNUP_FETCH_SUCCEEDED';
export const USER_FETCH_FAILED = 'USER_FETCH_FAILED';

export const SIGNIN_START = 'SIGNIN_START';
export const SIGNIN_FETCH_SUCCEEDED = 'SIGNIN_FETCH_SUCCEEDED';
export const USER_SIGN_IN_FAILED = 'USER_SIGN_IN_FAILED';

export const REDIRECT = 'REDIRECT';

export const INFO = 'INFO';
export const INFO_IN_FAILED = 'INFO_IN_FAILED';
